language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: spark-example-vmtenorio
  api_key:
    secure: OzW1b/c94kMCUJ5v4apT8oVTei49TDHU2HJtN0QvzLRp0uRsoTFiVAKTmWJ8h2iMSZAOmxYJN4F82AU3cvf2nIdj2iDtz5U9PO6vsajhGaRQWCJL3VsJQRAOSVXvzXqA4tTCQbWFq1ZidH3oAzHU/sLxxuAhgaUK6+6iURM8M3QLPX5uB9vN5VNpqzQSxAghRaanzV33oO3N3raJC2bSPON/sbeNRmaUqc6jErUVXcyNEsbhLkgZw0ylQxt3NvJ+Ub3iEb5o4kJ4aqE9Rw1aMUyr3lSz3Gz0s0whQd6AByL4LK0wUWnAUOb6GpT4RrcXpZHMVuf4mKz0Z9v3EJo8xYpjrDjSdzecqw6LHd/w5GnDxVfDkwW0mb5QZJj6blmbW2SUjsTlOuypMXyv7jyEK3yWE7VoqC79F2beZugNCY38kRRClSQX7CoUmBdw4Ss01Qczbi0wiRst2b1lWGlEfnr94UzYl/tNZKVyqQBJ2rMxeDedvRg7Bo/jaIDsLorlni+gUSlcUil+mEdOuVSsOZSMZfQv7c016FVG+pKELBF2CBPFFjFn1hqjYp5TB2mH4RQhM6PtHpER4vo3TtN4oi7WQQvnmyoq6vwCLdxkvWuCZcA3B34NZUGg2w831n3wUWY+kkd6zwH2DhhSdTc32MMstY6hXVlU5PA5PLk5re4=
